name: Scrooge testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup backend environment
      uses: ./.github/actions/setup-backend
      with:
        m2-cache-key: scrooge-testing

    - name: Check outdated dependencies
      run: clojure -M:outdated

    - name: Install dependencies
      run: clojure -P -M:dev:test

    - name: Lint project
      run: >-
        clj-kondo
        --config ./.clj-kondo/config-ci.edn
        --config-dir ./.clj-kondo
        --parallel
        --lint
        ./bases/api/src
        ./bases/api/test

    - name: Run tests
      run: clojure -X:dev:test

